### ISSUE TITLE
some question for help 

### ISSUE THREAD

**Issue by sytpb** [jherr/taming-useeffect#1]
hi jack ,  i don't know why i can't comment in youtube, maybe is the vpn issue . 
thanks for your wonderful video with useEffect . i leaned a lot from it .  I have watched several times . 

there are two question for me , form 17: 18 .  

1: why move the dependence onSuccess to the EffectLayout ?
"now anytime that options.onSuccess changes  this current will be updated and we'll  the most current value  in here regardless of the fact that this might already be in flight " --- ? ? 

2:  about the callback 
![image](https://user-images.githubusercontent.com/12178686/185581691-a3732b7b-e749-4972-ba5b-f9a3240a0e67.png)

why should do ref and EffectLayout  inside of callback function 

Thanks a lot !

**Comment by jherr** [comment]
There is a Blue Collar Coder Discord server where you can ask questions about the videos. https://discord.gg/sae4SWPAFN
